package org.usfirst.frc.team948.robot;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.interfaces.Accelerometer;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import org.usfirst.frc.team948.robot.NRGCANTalon;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public enum Direction {
		Left, Right;
	}

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static Accelerometer accelerometer;
	
	public static SpeedController victorLeft1;
	public static SpeedController victorRight1;
	public static SpeedController victorRight2;
	public static SpeedController victorLeft2;
	public static Gyro driveGyro;
	public static Encoder rightEncoder;
	public static Encoder leftEncoder;     

	public static NRGCANTalon lifterDart;
	public static AnalogPotentiometer scissorLiftPotentiometer;
	public static DigitalInput lowerLifterMovement;
	public static DigitalInput upperLifterMovement;
	public static AnalogInput backIR;
	
	public static SpeedController talonAcquirerRight;
	public static SpeedController talonAcquirerLeft;
	public static DoubleSolenoid leftAcquirerPiston;
	public static DoubleSolenoid rightAcquirerPiston;
	public static DoubleSolenoid pushPiston;
	public static DoubleSolenoid pincherPressurizer;
	
	public static DigitalInput binSensor;
	public static DigitalInput firstToteSensor;
	public static DigitalInput nextToteSensor;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// TODO: Assign ports to the encoders based upon electrical's decision

	// public static Encoder encoderLeft;

	public static void init() {
		backIR = new AnalogInput(0);
		
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		victorLeft1 = new Talon(2);
		LiveWindow.addActuator("Drive Subsystem",
				"Speed Controller Front Left Victor", (Talon) victorLeft1);

		victorRight1 = new Talon(0);
		LiveWindow.addActuator("Drive Subsystem",
				"Speed Controller Front Right Victor", (Talon) victorRight1);

		victorRight2 = new Victor(1);
		LiveWindow.addActuator("Drive Subsystem",
				"Speed Controller Back Right Victor", (Victor) victorRight2);

		victorLeft2 = new Victor(3);
		LiveWindow.addActuator("Drive Subsystem",
				"Speed Controller Back Left Victor", (Victor) victorLeft2);
		pincherPressurizer = new DoubleSolenoid(2, 3);

		driveGyro = new Gyro(1);
		LiveWindow.addSensor("Drive Subsystem", "Drive Gyro", driveGyro);
		if (Robot.contestRobot) {
			driveGyro.setSensitivity(0.007 );
		} else {
			driveGyro.setSensitivity(0.007* 353/360);
		}
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

		rightEncoder = new Encoder(0, 1);
		if (Robot.contestRobot) {
			rightEncoder.setDistancePerPulse(10.125 / 16038);
		} else {
			rightEncoder.setDistancePerPulse(1 / 1639.5);
		}
		LiveWindow.addSensor("Drive Subsystem", "Right Side Encoder",
				(Encoder) rightEncoder);
		leftEncoder = new Encoder(2, 3, true);
		if (Robot.contestRobot) {
			leftEncoder.setDistancePerPulse(10.125 / 16405);
		} else {
			leftEncoder.setDistancePerPulse(1 / 1639.5);
		}

		leftEncoder.setReverseDirection(false);
		LiveWindow.addSensor("Drive Subsystem", "Left Side Encoder",
				(Encoder) leftEncoder);

		lowerLifterMovement = new DigitalInput(4);
		upperLifterMovement = new DigitalInput(5);
		
		binSensor = new DigitalInput(6);
		firstToteSensor = new DigitalInput(7);
		nextToteSensor = new DigitalInput(8);
		LiveWindow.addSensor("Acquirer", "Bin Sensor", binSensor);
		LiveWindow.addSensor("Acquirer", "1st Tote Sensor", firstToteSensor);
		LiveWindow.addSensor("Acquirer", "Next Tote Sensor", nextToteSensor);
		
		scissorLiftPotentiometer = new AnalogPotentiometer(2);
		lifterDart = new NRGCANTalon(1);
		LiveWindow.addSensor("Scissor Lift Subsystem",
				"Scissor Lift Potentiometer",
				(AnalogPotentiometer) scissorLiftPotentiometer);
		LiveWindow
				.addSensor("Scissor Lift Subsystem",
						"Scissor Lift Upper Switch",
						(DigitalInput) upperLifterMovement);
		LiveWindow
				.addSensor("Scissor Lift Subsystem",
						"Scissor Lift Lower Switch",
						(DigitalInput) lowerLifterMovement);
		lifterDart.enableControl();
		LiveWindow.addActuator("Scissor Lift Subsystem", "LifterDart",
				lifterDart);

		talonAcquirerLeft = new Victor(5);
		talonAcquirerRight = new Victor(4);

		leftAcquirerPiston = new DoubleSolenoid(6, 7);
		rightAcquirerPiston = new DoubleSolenoid(4, 5);
		LiveWindow.addActuator("Pincher Subsytem", "Left Pincher Piston",
				leftAcquirerPiston);
		LiveWindow.addActuator("Pincher Subsystem", "Right Pincher Piston",
				rightAcquirerPiston);
		
		pushPiston = new DoubleSolenoid(0, 1);
		LiveWindow.addActuator("Acquirer Subsystem", "Push Piston",
				pushPiston);

	}
}